### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by ploth** [rbaron/dict.cc.py#19]
Am I the only one? Since today it raises the following error:

```bash
Traceback (most recent call last):
  File "/home/tlothpa/venv/dictcc/bin/dict.cc.py", line 81, in <module>
    run()
  File "/home/tlothpa/venv/dictcc/bin/dict.cc.py", line 62, in run
    args.output_language)
  File "/home/tlothpa/venv/dictcc/lib/python3.6/site-packages/dictcc/dictcc.py", line 59, in translate
    response_body = cls._get_response(word, from_language, to_language)
  File "/home/tlothpa/venv/dictcc/lib/python3.6/site-packages/dictcc/dictcc.py", line 76, in _get_response
    res = urllib2.urlopen(req).read()
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by aaschmid** [comment]
Still working here, what command do you call @ploth?

**Comment by rbaron** [comment]
hi @ploth. Not sure if you solved it, but could it be that you're behind a proxy?

**Comment by ploth** [comment]
Yes I'm behind a proxy (company) but it stopped working 3 days ago. I don't know why it was working before.

**Comment by aaschmid** [comment]
Can you access https://www.dict.cc/ in your browser still? I assume so, so can you access it using `curl` or `wget`?

**Comment by aaschmid** [comment]
An using `python` and `requests` fails

```echo -e "import requests\nprint(requests.get('https://dict.cc/'))" | python```

???

**Comment by rbaron** [comment]
@ploth another thing to try is to set the `HTTPS_PROXY` environment variable with the proxy your company uses. For example:

```
$ HTTPS_PROXY=http://my_proxy:my_port dict.cc.py en de body
```

**Comment by ploth** [comment]
> An using python and requests fails
echo -e "import requests\nprint(requests.get('https://dict.cc/'))" | python
???

```zsh
$ echo -e "import requests\nprint(requests.get('https://dict.cc/'))" | python
<Response [200]>
```

> @ploth another thing to try is to set the HTTPS_PROXY environment variable with the proxy your company uses.

`http_proxy` and `https_proxy` environment variables are already set.

**Comment by rbaron** [comment]
Ah, I see. Looks like we're using `urllib2` to make the HTTP request to dict.cc [[0]](https://github.com/rbaron/dict.cc.py/blob/master/dictcc/dictcc.py#L71). It doesn't seem to know about proxy environment variables [[1]](https://stackoverflow.com/a/1450154).

I think we have two reasonable approaches:

1. Update the code to use `requests`;
2. Implement the proxy-switching logic based on the `HTTPS_PROXY` environment variable ourselves and use the stackoverflow solution.

I would lean towards approach 1, because it seems simpler and more standard. If you guys want to try and submit a PR, that would be great. Otherwise, I can do it a bit later today.

**Comment by aaschmid** [comment]
wasn't aware that we haven't used `requests` anyway but see #21 which does it not ;-)

**Comment by rbaron** [comment]
Thanks @aaschmid. @ploth, let us know if it works! 😃

**Comment by ploth** [comment]
It is working now. Thanks!
But it is strange that this doesn't work any more https://github.com/rbaron/dict.cc.py/commit/35aea3b8094dda7f27c96e74a472aec955a972ce

**Comment by aaschmid** [comment]
Don't get what you mean @ploth ?

**Comment by ploth** [comment]
Its missing those spaces for an unknown reason between the dots and the vocables.

```zsh
body..............Körper
```
instead of
```zsh
body .............. Körper
```

**Comment by aaschmid** [comment]
Ah ok, works for me using the latest `master`, installing via `makepkg -i` on Archlinux. How do you use it?

**Comment by ploth** [comment]
Installed from `pip`

**Comment by aaschmid** [comment]
thats the issue, pip does not have the latest version containing the wanted changes, see https://pypi.org/project/dict.cc.py/. The version in `pip` is from October 2016...

**Comment by ploth** [comment]
But we want to have a newer version on `pip`? I would maintain it.

**Comment by aaschmid** [comment]
@rbaron it is your repo, any thoughts?
